apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: video-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: api
          image: localhost:32000/go-streaming-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-env
          volumeMounts:
            - name: videos-public
              mountPath: /app/public/videos
      volumes:
        - name: videos-public
          persistentVolumeClaim:
            claimName: pvc-videos-processed
