apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-create-topic
  namespace: video-streaming
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: kafka-topic-creator
          image: bitnami/kafka:3.6
          command:
            - /bin/bash
            - -c
            - |
              /opt/bitnami/kafka/bin/kafka-topics.sh \
                --create \
                --topic process-topic \
                --bootstrap-server kafka:9092 \
                --partitions 1 \
                --replication-factor 1 \
                --config retention.ms=3600000 \
                --if-not-exists

