apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-videos
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  hostPath:
    path: /mnt/videos

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kafka
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  hostPath:
    path: /mnt/kafka

