apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-videos
  namespace: video-streaming
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""

