apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-videos
  namespace: video-streaming
spec:
  volume: pv-videos
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-videos-processed
  namespace: video-streaming
spec:
  volume: pv-videos-processed
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""

