apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  namespace: video-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
        - name: processor
          image: localhost:32000/go-streaming-processor
          imagePullPolicy: Always
          resources:
            requests:
              # Reserve roughly half a physical core
              cpu: "2000m"
              # Reserve 3 GiB of RAM
              memory: "4Gi"
              # Ensure at least 5 GiB ephemeral storage for HLS segments
              ephemeral-storage: "15Gi"
            limits:
              # Allow up to ~4 full cores if available
              cpu: "4000m"
              # Cap at 6 GiB to avoid starving the OS
              memory: "8Gi"
              ephemeral-storage: "20Gi"
          envFrom:
            - configMapRef:
                name: processor-env
          volumeMounts:
            - name: videos-volume
              mountPath: /watch
            - name: videos-processed
              mountPath: /processed
      volumes:
        - name: videos-volume
          persistentVolumeClaim:
            claimName: pvc-videos
        - name: videos-processed
          persistentVolumeClaim:
            claimName: pvc-videos-processed
