apiVersion: v1
kind: ConfigMap
metadata:
  name: processor-env
  namespace: video-streaming
data:
  OUTPUT_DIR: /processed
  KAFKA_TOPIC: process-topic
  KAFKA_BROKER: 192.168.0.242:9094
  POSTGRES_DSN: "host=192.168.0.241 user=admin password=admin dbname=video-streaming port=5432 sslmode=disable TimeZone=UTC"

