apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher
  namespace: video-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watcher
  template:
    metadata:
      labels:
        app: watcher
    spec:
      containers:
        - name: watcher
          image: localhost:32000/go-streaming-watcher
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: watcher-env
          volumeMounts:
            - name: videos-volume
              mountPath: /watch
      volumes:
        - name: videos-volume
          persistentVolumeClaim:
            claimName: pvc-videos

