apiVersion: v1
kind: ConfigMap
metadata:
  name: watcher-env
  namespace: video-streaming
data:
  WATCH_DIR: /watch
  KAFKA_TOPIC: process-topic
  KAFKA_BROKER: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092

