apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: video-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox:latest
          command: ["sh","-c","chown -R 1001:1001 /bitnami/zookeeper"]
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: zookeeper-data
              mountPath: /bitnami/zookeeper

      containers:
        - name: zookeeper
          image: bitnami/zookeeper:3.8
          ports:
            - containerPort: 2181
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          volumeMounts:
            - name: zookeeper-data
              mountPath: /bitnami/zookeeper
      volumes:
        - name: zookeeper-data
          persistentVolumeClaim:
            claimName: pvc-zookeeper
